sudo: required
dist: trusty
language: C

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.8
    # install additional tools
    - clang-format-3.8

matrix:
  include:
    - os: osx
      compiler: clang-3.8
    - os: osx
      compiler: clang-3.8
      env: BUILD_OPT=1
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      env: BUILD_OPT=1
    - os: linux
      compiler: gcc
      env: USE_ASAN=1
    - os: linux
      env: CLANG_FORMAT=1
  allow_failures:
    - env: CLANG_FORMAT=1

env:
  global:
    - USE_64=1
    - NSS_ENABLE_TLS_1_3=1
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; CC=gcc-5 CCC=g++-5; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; CC=clang-3.8 CCC=clang++-3.8; fi

install:
  - hg clone https://hg.mozilla.org/projects/nspr ../nspr
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install llvm38; fi

script:
  - if [ -n "$CLANG_FORMAT" ]; then automation/travis/validate-formatting.sh lib/ssl; exit $?; fi
  - make nss_build_all
  - cd tests; NSS_TESTS="ssl_gtests pk11_gtests der_gtests util_gtests" NSS_CYCLES=standard ./all.sh

notifications:
  irc:
    channels:
      - "irc.mozilla.org:6697/#nssbot"
    nick: travisci-franziskus
    on_success: change
    on_failure: always
