sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-3.8
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.8
    # install additional tools
    - clang-format-3.8

matrix:
  include:
    - os: osx
      compiler: clang-3.8
    - os: osx
      compiler: clang-3.8
      env: BUILD_OPT=1
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      env: BUILD_OPT=1
    - os: linux
      env: CLANG_FORMAT=1
  allow_failures:
    - env: CLANG_FORMAT=1

before install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CC="gcc-5"; export CCC="g++-5"; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; brew install llvm38; fi;

install:
  - hg clone https://hg.mozilla.org/projects/nspr ../nspr

script:
  - if [ -n "$CLANG_FORMAT" ];
    then
      cd nss;
      automation/travis/subdir-clang-format.sh lib/ssl;
      automation/travis/subdir-clang-format-diff.sh lib/ssl;
      exit $?;
    fi
  - pwd; cd nss
  - gcc --version; g++ --version; CC --version; CCC --version
  - pwd; USE_64=1 NSS_ENABLE_TLS_1_3=1 make nss_build_all
  - cd tests; USE_64=1 NSS_ENABLE_TLS_1_3=1 NSS_TESTS="ssl_gtests pk11_gtests der_gtests util_gtests" NSS_CYCLES=standard ./all.sh
