sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.8
    # install additional tools
    - clang-format-3.8

matrix:
  include:
    - os: osx
      compiler: clang-3.8
      env:
        - CC=clang-3.8
        - CCC=clang++-3.8
    - os: osx
      compiler: clang-3.8
      env:
        - CC=clang-3.8
        - CCC=clang++-3.8
        - BUILD_OPT=1
    - os: linux
      compiler: gcc
      env:
        - CC=gcc-5
        - CCC=g++-5
    - os: linux
      compiler: gcc
      env:
        - CC=gcc-5
        - CCC=g++-5
        - BUILD_OPT=1
    - os: linux
      compiler: gcc
      env:
        - CC=gcc-5
        - CCC=g++-5
        - USE_ASAN=1
    - os: linux
      env: CLANG_FORMAT=1
  allow_failures:
    - env: CLANG_FORMAT=1

install:
  - hg clone https://hg.mozilla.org/projects/nspr ../nspr

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install llvm38; fi
  - if [ -n "$CLANG_FORMAT" ];
    then
      automation/travis/subdir-clang-format.sh lib/ssl;
      automation/travis/subdir-clang-format-diff.sh lib/ssl;
      exit $?;
    fi
  - gcc --version; g++ --version;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then $CC --version; $CCC --version; fi
  - USE_64=1 NSS_ENABLE_TLS_1_3=1 make nss_build_all
  - cd tests; USE_64=1 NSS_ENABLE_TLS_1_3=1 NSS_TESTS="ssl_gtests pk11_gtests der_gtests util_gtests" NSS_CYCLES=standard ./all.sh
