os: Visual Studio 2015

install:
  - cinst mozillabuild

build:
  # - choco install mozillabuild
  - hg clone https://hg.mozilla.org/projects/nspr C:\projects\nspr
  - xcopy C:\projects\nss\automation\start-shell-msvc2015-x64.bat C:\mozilla-build\ /Y
  - xcopy C:\projects\nss\automation\start-shell.bat C:\mozilla-build\ /Y
  - C:\mozilla-build\start-shell-msvc2015-x64.bat /c/projects/nss/automation/appveyor-build.sh

test: off

deploy: off

# debugging - remove if working
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
